"""Build-time GUI preference (generated by tools/build_exe.py).

Do not edit by hand - it is overwritten on every build. The committed
value is None, meaning auto-detect at runtime.
"""

from __future__ import annotations

# "tk", "toga" or None (auto-detect at runtime).
DEFAULT_GUI: str | None = None
