#!/usr/bin/env python3
"""Build every Windows deliverable and verify each one actually starts.

Produces, in ``dist/``:

  * ``rec检查喵.exe``                 tkinter, single file (primary)
  * ``rec检查喵/``                    tkinter, folder - nothing unpacked at startup
  * ``rec检查喵-portable.zip``        the folder, zipped for handing over
  * ``rec检查喵-toga.exe``            Toga build (x64 Windows only)
  * ``使用说明.txt``                  generated from the real artifact names

Design notes
------------
* **No renaming after the fact.** Each spec names its own output, so the tkinter
  build can no longer be clobbered by the Toga build writing the same filename.
  An earlier version built both as ``MiRecoveryHelper.exe`` and renamed
  afterwards, which silently destroyed the primary deliverable when the build
  order changed.
* **Instructions are generated**, not hand-written, so they cannot describe a
  layout that no longer exists. (They did: the shipped text told users to run
  ``MiRecoveryHelper\\MiRecoveryHelper.exe`` after both names had changed.)
* **``_buildcfg`` is written before building** so the frozen app knows which GUI
  it was built for. Setting an environment variable inside a spec, as an earlier
  version did, has no effect on the built executable.

Usage
-----
    python tools/build_exe.py              # everything + self test
    python tools/build_exe.py --tk-only
    python tools/build_exe.py --no-art     # build without third-party artwork
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DIST = PROJECT_ROOT / "dist"
BUILD = PROJECT_ROOT / "build"
VENV_PYTHON = PROJECT_ROOT / ".venv" / "Scripts" / "python.exe"

sys.path.insert(0, str(PROJECT_ROOT / "src"))
from mirecovery import theme  # noqa: E402
from mirecovery.logsetup import log_directory  # noqa: E402

TK_ONEFILE_SPEC = "MiRecoveryHelper-tk.spec"
TK_ONEDIR_SPEC = "MiRecoveryHelper-tk.onedir.spec"
TOGA_ONEFILE_SPEC = "MiRecoveryHelper.spec"
SELFTEST_SPEC = "MiRecoveryHelper.selftest.spec"

APP_NAME = theme.EXE_BASENAME                 # rec检查喵
TOGA_NAME = f"{APP_NAME}-toga"
SELFTEST_NAME = f"{APP_NAME}-selftest"

# Only artifacts this script owns may be deleted from dist/.
MANAGED_ARTIFACTS = (
    f"{APP_NAME}.exe",
    f"{TOGA_NAME}.exe",
    f"{SELFTEST_NAME}.exe",
    SELFTEST_NAME,
    f"{APP_NAME}-portable.zip",
    APP_NAME,
    "使用说明.txt",
    # Names from earlier revisions, removed so stale builds cannot be mistaken
    # for current ones.
    "MiRecoveryHelper.exe",
    "MiRecoveryHelper-toga.exe",
    "MiRecoveryHelperSelfTest.exe",
    "MiRecoveryHelper-portable.zip",
    "MiRecoveryHelper",
)


def python_executable() -> str:
    if VENV_PYTHON.is_file():
        return str(VENV_PYTHON)
    return sys.executable


def run_pyinstaller(spec: str, workpath: str) -> int:
    command = [
        python_executable(), "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--distpath", str(DIST),
        "--workpath", str(BUILD / workpath),
        str(PROJECT_ROOT / spec),
    ]
    print(f"[build] {spec}")
    result = subprocess.run(command, cwd=PROJECT_ROOT)
    if result.returncode != 0:
        print(f"[build] {spec} 失败（退出码 {result.returncode}）")
    return result.returncode


def write_buildcfg(gui: str | None) -> None:
    """Record the intended GUI so the frozen app prefers it at startup."""
    target = PROJECT_ROOT / "src" / "mirecovery" / "_buildcfg.py"
    literal = f'"{gui}"' if gui else "None"
    target.write_text(
        '"""Build-time GUI preference (generated by tools/build_exe.py).\n\n'
        "Do not edit by hand - it is overwritten on every build. The committed\n"
        "value is None, meaning auto-detect at runtime.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        '# "tk", "toga" or None (auto-detect at runtime).\n'
        f"DEFAULT_GUI: str | None = {literal}\n",
        encoding="utf-8",
    )
    print(f"[build] _buildcfg.DEFAULT_GUI = {literal}")


def clean_dist() -> None:
    """Remove only artifacts this script owns."""
    for name in MANAGED_ARTIFACTS:
        target = DIST / name
        if target.is_dir():
            shutil.rmtree(target, ignore_errors=True)
        elif target.is_file():
            target.unlink()


def prepare_data() -> None:
    """Regenerate kb.json and image_refs.json so the build is never stale."""
    for script in ("build_kb.py", "build_references.py"):
        result = subprocess.run(
            [python_executable(), str(PROJECT_ROOT / "tools" / script)],
            cwd=PROJECT_ROOT,
        )
        if result.returncode != 0:
            raise SystemExit(f"{script} 失败，构建中止")


def verify_frozen() -> bool:
    print("[verify] 冻结自检")
    if run_pyinstaller(SELFTEST_SPEC, "selftest") != 0:
        return False

    # onedir: no runtime extraction, so this works even when %TEMP% is tight.
    self_test = DIST / f"{SELFTEST_NAME}" / f"{SELFTEST_NAME}.exe"
    if not self_test.is_file():
        print(f"[verify] 找不到自检程序：{self_test}")
        return False

    # Keep any incidental temp use inside the project.
    env = dict(os.environ)
    scratch = BUILD / "run-tmp"
    scratch.mkdir(parents=True, exist_ok=True)
    env["TEMP"] = env["TMP"] = str(scratch)

    result = subprocess.run(
        [str(self_test)],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        # The self test emits UTF-8 (it reconfigures its own streams, because the
        # console here is GBK and cannot encode the UI's ✅/❌). Decoding its output
        # with the locale codec mangled it, so the build reported "self test
        # failed" while the test itself had printed SELFTEST OK.
        encoding="utf-8",
        errors="replace",
        env=env,
    )
    output = (result.stdout or "") + (result.stderr or "")
    print(output.strip())
    return result.returncode == 0 and "SELFTEST OK" in output


def zip_folder(folder: Path, archive: Path) -> Path | None:
    if not folder.is_dir():
        return None
    if archive.is_file():
        archive.unlink()
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as handle:
        for path in sorted(folder.rglob("*")):
            if path.is_file():
                handle.write(path, path.relative_to(DIST))
    return archive


def human(size: int) -> str:
    return f"{size / 1024 / 1024:.1f} MB"


def folder_size(folder: Path) -> int:
    return sum(p.stat().st_size for p in folder.rglob("*") if p.is_file())


def write_instructions(has_toga: bool, no_art: bool) -> Path:
    """Generate dist/使用说明.txt from the artifacts that actually exist."""
    lines = [
        f"  {theme.APP_DISPLAY_NAME}",
        "  小米 / 红米 刷机报错检查助手",
        "=" * 50,
        "",
        f"  内置形象：{theme.CHARACTER_NAME}（{theme.CHARACTER_ALIAS}）",
        "  完全离线运行 —— 日志和图片都不会离开你的电脑。",
        "",
        "",
        "选哪个文件用？",
        "-" * 14,
        f"  日常使用（推荐）： {APP_NAME}.exe",
        "      单文件，双击即可。界面用 tkinter，不依赖 .NET，启动快。",
        "",
        "  如果它报「Could not create temporary directory!」：",
        f"      改用 {APP_NAME}-portable.zip —— 解压后运行",
        f"      {APP_NAME}\\{APP_NAME}.exe",
        "      目录版启动时不解压任何东西，不依赖 %TEMP%，磁盘紧张也能用。",
        "",
    ]
    if has_toga:
        lines += [
            f"  仅在 64 位 x86 电脑上： {TOGA_NAME}.exe",
            "      Toga 界面版。ARM64 电脑上无法运行（原因见下）。",
            "",
        ]
    lines += [
        "",
        "怎么用？",
        "-" * 8,
        "  1. 丢一张报错截图（可选）—— 点「选择图片」，认得出来就直接给方案；",
        "  2. 或者把日志粘到输入框（SP Flash Tool / MiFlash / QFIL / fastboot /",
        "     recovery 的输出都行）；",
        "  3. 点「检查一下喵」看结果。",
        "",
        "",
        "关于 ARM64 电脑",
        "-" * 15,
        "  Toga 的 Windows 界面后端依赖 pythonnet，而 pythonnet 官方只提供",
        "  x86 / x64 运行时，没有 ARM64 版本。所以 Toga 界面在 ARM64 上必然报错：",
        "",
        "      RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize",
        "",
        "  这是位数/架构不匹配，属环境不兼容，改打包方式也解决不了；备选方案",
        "  （toga-webview2、pywebview）同样依赖 .NET。",
        "  因此主交付物用 Python 标准库自带的 tkinter 界面：不碰 .NET，功能一致。",
        "",
        "",
        "如果单文件版报临时目录错误",
        "-" * 26,
        "  说明 %TEMP% 写不进去或磁盘快满了。按顺序试：",
        "    1. 改用目录版（最省事，完全不依赖临时目录）；",
        "    2. 清理磁盘，或把 TEMP/TMP 指到空间充足的分区，再启动；",
        "    3. 暂时关闭杀毒软件实时防护再试。",
        "",
        "  排查命令（PowerShell）：",
        "      echo $env:TEMP         # 临时目录在哪",
        "      Test-Path $env:TEMP    # 必须是 True",
        "      Get-PSDrive C          # 剩余空间",
        "",
        "",
        "关于图片识别",
        "-" * 12,
        "  · 应用会**先读出图上的文字**（OCR），再用文字检索知识库 —— 所以它能分辨",
        "    截图里写的是 ERROR 4032 还是 ERROR 4004。",
        "  · 画面类型识别作为补充：OCR 读不出东西时（照片太糊），它会顶上来。",
        "  · 本构建内置 Windows 自带 OCR 引擎，离线可用，不需要联网。",
        "  · 若 OCR 读不出字，把报错文字直接粘到输入框，那比图片更可靠。",
        "",
        "",
        "关于知识库内容（重要）",
        "-" * 22,
        "  · 现有条目是依据通用维修经验整理的，没有真实工单/日志作为来源。",
        "  · 每条末尾的「待确认」小节列明了不确定的地方，动手前请先看。",
        "  · 刷机有风险，请先备份数据；拿不准就走官方售后。",
        "",
        "",
        "出问题时",
        "-" * 10,
        "  程序会写日志，位置：",
        f"      {log_directory() / 'app.log'}",
        "  把日志文件发出来比截图有用。",
        "",
        "",
        "关于图标与形象",
        "-" * 14,
    ]
    if no_art:
        lines.append("  本次构建未打包第三方美术资源（--no-art），图标为占位图形。")
    else:
        lines += [
            "  图标与界面形象来自用户提供的原图，未做裁剪或重绘。",
            "  该图是第三方作品（形象设定源自社区开源资产库），",
            "  对外分发或商用前请自行确认授权。",
        ]
    lines.append("")

    path = DIST / "使用说明.txt"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tk-only", action="store_true",
                        help="只构建 tkinter 版（跳过 Toga 版）")
    parser.add_argument("--skip-verify", action="store_true")
    parser.add_argument("--no-art", action="store_true",
                        help="不打包第三方美术资源（用于需要干净授权的构建）")
    parser.add_argument("--no-ocr", action="store_true",
                        help="不打包可选 OCR 引擎（winsdk 约 11 MB；磁盘紧张时用）")
    args = parser.parse_args(argv)

    if args.no_art:
        # The flag must reach the specs, which import spec_common at build time.
        os.environ["RECNEKO_NO_ART"] = "1"
    if args.no_ocr:
        os.environ["RECNEKO_NO_OCR"] = "1"

    DIST.mkdir(parents=True, exist_ok=True)
    BUILD.mkdir(parents=True, exist_ok=True)
    clean_dist()
    prepare_data()

    results: list[str] = []

    # ---- 1. tkinter single file (PRIMARY) --------------------------------
    write_buildcfg("tk")
    if run_pyinstaller(TK_ONEFILE_SPEC, "tk-onefile") != 0:
        return 1
    tk_exe = DIST / f"{APP_NAME}.exe"
    if not tk_exe.is_file():
        print(f"[build] 主交付物 {tk_exe.name} 未生成")
        return 1
    results.append(f"单文件 exe   : {tk_exe.name}  {human(tk_exe.stat().st_size)}")

    # ---- 2. tkinter folder ----------------------------------------------
    if run_pyinstaller(TK_ONEDIR_SPEC, "tk-onedir") != 0:
        return 1
    folder = DIST / APP_NAME
    if not (folder / f"{APP_NAME}.exe").is_file():
        print(f"[build] 目录版缺少 {APP_NAME}.exe")
        return 1
    results.append(f"目录版       : {folder.name}/  {human(folder_size(folder))}")

    archive = zip_folder(folder, DIST / f"{APP_NAME}-portable.zip")
    if archive:
        results.append(f"便携压缩包   : {archive.name}  {human(archive.stat().st_size)}")

    # ---- 3. verification (while _buildcfg still says tkinter) ------------
    # The self test bundles _buildcfg, so it must run while the tkinter value is
    # in place - otherwise it reports whatever the last build wrote, which is
    # how an earlier revision ended up testing a "toga" config.
    if not args.skip_verify:
        if not verify_frozen():
            print("\n[build] 冻结自检失败：打包结果不可用")
            return 1
        results.append("冻结自检     : 通过")

    # ---- 4. Toga build (x64 only) ---------------------------------------
    has_toga = False
    if not args.tk_only:
        write_buildcfg("toga")
        if run_pyinstaller(TOGA_ONEFILE_SPEC, "toga-onefile") == 0:
            toga_exe = DIST / f"{TOGA_NAME}.exe"
            if toga_exe.is_file():
                has_toga = True
                results.append(
                    f"Toga 版      : {toga_exe.name}  {human(toga_exe.stat().st_size)}"
                    "（仅 x64 可用）"
                )
        else:
            print("[build] Toga 版构建失败（不影响主交付物）")

    # ---- 5. generated instructions --------------------------------------
    info = write_instructions(has_toga, args.no_art)
    results.append(f"使用说明     : {info.name}")

    # ---- 6. assert the primary deliverables survived --------------------
    if not tk_exe.is_file() or not (folder / f"{APP_NAME}.exe").is_file():
        print("\n[build] 严重错误：主交付物在构建结束时不存在")
        return 1

    # ---- 7. leave the tree in its neutral state -------------------------
    # _buildcfg.py is a build artifact; committing "toga" would make a later
    # manual `pyinstaller MiRecoveryHelper-tk.spec` prefer a backend it does not
    # contain.
    write_buildcfg(None)

    print("\n构建完成：")
    for line in results:
        print(f"  {line}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
