#!/usr/bin/env python3
"""Offline smoke test for the retrieval engine.

Runs without Toga, so it works in a plain Python environment:

    python tools/smoke_test.py

Exits non-zero if any expectation fails.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from mirecovery.kb import KB  # noqa: E402
from mirecovery.report import build_report  # noqa: E402
from mirecovery.scanner import analyze  # noqa: E402

# (pasted log sample, expected platform, substring expected in the top hit's slug/title)
CASES: list[tuple[str, str, str]] = [
    (
        """SP Flash Tool v5.2044
BROM ERROR : S_FT_ENABLE_DRAM_FAIL (4032)
[EMI] Enable DRAM failed!
""",
        "mtk",
        "4032",
    ),
    (
        """ERROR: Sahara Fail
Failed to get sahara mode!!
Invalid Firehose programmer
""",
        "qualcomm",
        "sahara",
    ),
    (
        """$ fastboot flash boot boot.img
Sending 'boot' (65536 KB)                            OKAY [  1.532s]
Writing 'boot'                                       FAILED (remote: 'not allowed in locked state')
fastboot: error: Command failed
""",
        "fastboot",
        "locked",
    ),
    (
        """E:failed to mount /data (Invalid argument)
E:Unable to mount storage
Can't load Android system. Your data may be corrupt.
""",
        "recovery",
        "data",
    ),
    (
        """dm-verity corruption
Your device is corrupt. It can't be trusted and may not work properly.
AVB: vbmeta verification failed
""",
        "avb",
        "vbmeta",
    ),
    (
        """$ fastboot devices
< waiting for any device >
""",
        "fastboot",
        "device",
    ),
    (
        """Only nop and sig tag can be received before authentication
""",
        "qualcomm",
        "auth",
    ),
    (
        """BROM ERROR : STATUS_BROM_CMD_SEND_DA_FAIL
""",
        "mtk",
        "da",
    ),
]


def main() -> int:
    kb = KB.load(PROJECT_ROOT / "src" / "mirecovery" / "data" / "kb.json")
    print(f"知识库加载成功：{len(kb.entries)} 条，版本 {kb.version}")
    print(f"平台：{', '.join(kb.platforms())}\n")

    failures = 0
    for index, (log, want_platform, want_in_hit) in enumerate(CASES, start=1):
        finding, matches, _ = build_report(kb, log, limit=3)
        top = matches[0].entry if matches else None
        top_label = top.title if top else "<无匹配>"
        ok_platform = finding.platform == want_platform
        ok_hit = bool(
            matches
            and (
                want_in_hit.lower() in matches[0].entry.slug.lower()
                or want_in_hit.lower() in matches[0].entry.title.lower()
                or want_in_hit.lower() in matches[0].entry.platform.lower()
            )
        )
        status = "PASS" if (ok_platform and ok_hit) else "FAIL"
        if status == "FAIL":
            failures += 1
        print(f"[{status}] 用例{index}: 判定={finding.platform} (期望 {want_platform}) "
              f"命中='{want_in_hit}' 置信度={finding.confidence}")
        print(f"         首选方案: {top_label}")
        if not ok_platform or not ok_hit:
            print(f"         匹配详情: {[ (m.entry.slug, m.score) for m in matches ]}")

    # Negative case: nonsense input should not crash and should not fake a platform.
    finding = analyze("hello world 你好")
    if finding.platform != "unknown":
        print(f"[FAIL] 无关文本被误判为 {finding.platform}")
        failures += 1
    else:
        print("[PASS] 无关文本正确判定为 unknown")

    # Empty input must be handled gracefully.
    empty_finding, empty_matches, empty_text = build_report(kb, "", limit=3)
    if empty_matches or not empty_text:
        print("[FAIL] 空输入处理异常")
        failures += 1
    else:
        print("[PASS] 空输入处理正常")

    failures += image_recognition_checks(kb)

    print(f"\n结果：{'全部通过' if failures == 0 else f'{failures} 个用例失败'}")
    return 1 if failures else 0


def image_recognition_checks(kb) -> int:
    """Exercise the screen recogniser end to end, if the image set exists.

    Requires kb/image_refs/ (generated by tools/make_reference_images.py); the
    CI test job does not generate that, so this section skips cleanly there.
    """
    ref_dir = PROJECT_ROOT / "kb" / "image_refs" / "synthetic"
    bench_dir = PROJECT_ROOT / "kb" / "image_refs" / "benchmark"
    if not ref_dir.is_dir() or not bench_dir.is_dir():
        print("[SKIP] 图片识别检查（未生成 kb/image_refs/，"
              "先跑 tools/make_reference_images.py）")
        return 0

    from mirecovery.imagefeatures import Reference, ReferenceLibrary, extract_path
    from mirecovery.recognize import ScreenRecognizer

    sys.path.insert(0, str(PROJECT_ROOT / "tools"))
    from make_reference_images import SCREENS

    failures = 0

    # Build the library in memory from the synthetic references.
    references = []
    for spec in SCREENS:
        directory = ref_dir / spec["label"]
        if not directory.is_dir():
            continue
        for image_path in sorted(directory.glob("*")):
            if image_path.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
                continue
            references.append(
                Reference(
                    label=spec["label"],
                    title=spec["title"],
                    kb_slug=spec["kb_slug"],
                    source="synthetic",
                    path=str(image_path.relative_to(PROJECT_ROOT)),
                    features=extract_path(image_path),
                )
            )
    if not references:
        print("[SKIP] 图片识别检查（参考图为空）")
        return 0

    recognizer = ScreenRecognizer(ReferenceLibrary(references=references))

    # Every reference must map to a real knowledge-base page.
    known_slugs = {entry.slug for entry in kb.entries}
    missing = sorted({r.kb_slug for r in references} - known_slugs)
    if missing:
        print(f"[FAIL] 参考图指向不存在的知识库页面: {missing}")
        failures += 1
    else:
        print(f"[PASS] {len(references)} 张参考图全部指向有效知识库页面")

    # Recognise one augmented image per class: anything ACCEPTED must be right.
    valid_labels = {spec["label"] for spec in SCREENS}
    samples = []
    for label_dir in sorted(bench_dir.iterdir()):
        if label_dir.is_dir() and label_dir.name in valid_labels:
            images = sorted(label_dir.glob("*"))
            if images:
                samples.append((label_dir.name, images[0]))

    accepted = accepted_correct = 0
    for expected, image_path in samples:
        result = recognizer.recognize_path(image_path)
        if result.matched:
            accepted += 1
            if result.label == expected:
                accepted_correct += 1
            else:
                print(f"[FAIL] {image_path.name}: 期望 {expected} 却判为 {result.label}")
                failures += 1
        else:
            # Declining is the safe outcome, but it must be a decision and not
            # a crash or an empty result.
            if not result.reason:
                print(f"[FAIL] {image_path.name}: 拒绝但没有给出原因")
                failures += 1

    if accepted == 0:
        print("[FAIL] 所有基准图都被拒绝，识别流程可能失效")
        failures += 1
    else:
        ok = accepted_correct == accepted
        print(f"[{'PASS' if ok else 'FAIL'}] 图片识别：接受 {accepted}/{len(samples)}，"
              f"其中正确 {accepted_correct}（接受即必须正确）")

    # A blank image must be declined rather than force-matched.
    from PIL import Image

    blank_result = recognizer.recognize_image(Image.new("RGB", (400, 800), (0, 0, 0)))
    if blank_result.matched:
        print(f"[FAIL] 纯黑空白图被误判为 {blank_result.label}")
        failures += 1
    else:
        print("[PASS] 纯黑空白图被正确拒绝")

    return failures


if __name__ == "__main__":
    raise SystemExit(main())
